# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lti", "0004_grouprole"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugResource",
            fields=[
                (
                    "resource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lti.Resource",
                    ),
                ),
            ],
            options={"manager_inheritance_from_future": True,},
            bases=("lti.resource",),
        ),
        migrations.RemoveField(model_name="resource", name="context",),
        migrations.RemoveField(model_name="resource", name="target",),
    ]
